"""Export managed config as a dnsmasq file (works on OpenWrt, Pi-hole, many routers). Review before applying."""
import ipaddress
from landar import storage
from landar.services import audit
from landar.services.guard import require

def render_dnsmasq(networks, scopes, reservations, records, forwarders) -> str:
    L = [f"# Generated by LANDAR on {audit.now()} UTC. Review before applying.", ""]
    if forwarders: L.append("no-resolv"); L += [f"server={f['address']}" for f in forwarders]; L.append("")
    by_net = {n["id"]: n for n in networks}
    for s in scopes:
        n = by_net[s["network_id"]]; net = ipaddress.ip_network(n["cidr"]); tag = f"net{n['id']}"
        L.append(f"# {n['name']}" + (f" (VLAN {n['vlan_id']})" if n["vlan_id"] else "") + f" {n['cidr']}")
        pre = "" if s["enabled"] else "# disabled: "
        L.append(f"{pre}dhcp-range=set:{tag},{s['range_start']},{s['range_end']},{net.netmask},{s['lease_hours']}h")
        if n["gateway"]: L.append(f"{pre}dhcp-option=tag:{tag},3,{n['gateway']}")
        if s["dns_servers"]: L.append(f"{pre}dhcp-option=tag:{tag},6,{s['dns_servers'].replace(' ', '')}")
        L.append("")
    if reservations: L.append("# Reservations"); L += [f"dhcp-host={r['mac']},{r['ip']}" + (f",{r['hostname']}" if r["hostname"] else "") for r in reservations]; L.append("")
    if records: L.append("# Local DNS records"); L += [f"host-record={r['name']},{r['ip']}" for r in records]; L.append("")
    return "\n".join(L)

def dnsmasq_config(actor) -> str:
    require(actor, "network.view")
    with storage.connect() as c:
        q = lambda s: [dict(r) for r in c.execute(s)]
        text = render_dnsmasq(q("SELECT * FROM networks"), q("SELECT * FROM dhcp_scopes"), q("SELECT * FROM dhcp_reservations"), q("SELECT * FROM dns_records"), q("SELECT * FROM dns_forwarders"))
        audit.record(c, actor.username, "config_exported", "dnsmasq"); return text
